# Use the official Maven/Java 11 image
FROM mcr.microsoft.com/vscode/devcontainers/java:0-11

# Copy the project files into the container
COPY . /workspace

# Change to the workspace directory
WORKDIR /workspace